### ISSUE TITLE
getting NoMethodError: undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by jiggneshhgohel** [fog/fog-google#124]
**Ruby: 2.3.0**
**Rails: 4.2.5**
**Paperclip: 4.3.6**
**fog-google: 0.3.1**

In my Rails app I am using Paperclip for file uploads and using Paperclip's Fog storage for 
uploading the files to Google Cloud.

I am facing an error `NoMethodError: undefined method `keys' for nil:NilClass` **while trying to update an already uploaded image file** on my Google Cloud Storage Bucket

**Photo** model:

```
class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  has_attached_file :photo

  validates_attachment_presence :photo
  validates_attachment_content_type :photo, content_type: /\Aimage/
  validates_attachment_file_name :photo, matches: [/png\Z/, /jpe?g\Z/]
  validates_attachment_size :photo, less_than_or_equal_to: 2.megabytes

  validates_presence_of :imageable

  validates_uniqueness_of :imageable_id, scope: :imageable_type, message: 'photo already exists', case_sensitive: false

  def url(photo_style: nil)
    case photo_style
      when :medium
        photo.url(:medium)
      when :thumbnail
        photo.url(:thumbnail)
      else
        photo.url
    end
  rescue Exception => e
    Rails.logger.error "Exception occurred while trying to fetch url for Photo(##{self.id}). Exception message: #{e.message}"
    Rails.logger.error "Returning Paperclip's default_url for Photo(##{self.id})."
    photo.options[:default_url]
  end
end
```

Below is the output of my rails console which shows the stack trace pointing to line `fog-google-0.3.1/lib/fog/storage/google_xml/real.rb:66` in this gem:

```
Loading development environment (Rails 4.2.5)
2.3.0 :001 > p = Photo.find(9)
  Photo Load (0.8ms)  SELECT  "photos".* FROM "photos" WHERE "photos"."id" = $1 LIMIT 1  [["id", 9]]
 => #<Photo id: 9, imageable_type: "Profile", imageable_id: 19, created_at: "2016-05-20 14:19:46", updated_at: "2016-05-20 14:19:46", photo_file_name: "2.png", photo_content_type: "image/png", photo_file_size: 1764904, photo_updated_at: "2016-05-20 14:19:45">
2.3.0 :002 > p.photo
 => #<Paperclip::Attachment:0x000000065ff8d8 @name=:photo, @name_string="photo", @instance=#<Photo id: 9, imageable_type: "Profile", imageable_id: 19, created_at: "2016-05-20 14:19:46", updated_at: "2016-05-20 14:19:46", photo_file_name: "2.png", photo_content_type: "image/png", photo_file_size: 1764904, photo_updated_at: "2016-05-20 14:19:45">, @options={:convert_options=>{}, :default_style=>:original, :default_url=>"/assets/generic-avatar.png", :escape_url=>true, :restricted_characters=>/[&$+,\/:;=?@<>\[\]\{\}\|\\\^~%# ]/, :filename_cleaner=>nil, :hash_data=>":class/:attachment/:id/:style/:updated_at", :hash_digest=>"SHA1", :interpolator=>Paperclip::Interpolations, :only_process=>[], :path=>"user_profile_photos/:id/:style/:filename", :preserve_files=>false, :processors=>[:thumbnail], :source_file_options=>{}, :storage=>:fog, :styles=>{:medium=>"250x150#", :thumb=>"450x350#"}, :url=>":fog_public_url", :url_generator=>Paperclip::UrlGenerator, :use_default_time_zone=>true, :use_timestamp=>true, :whiny=>true, :validate_media_type=>true, :check_validity_before_processing=>true, :fog_credentials=>{:provider=>"Google", :google_storage_access_key_id=>"<ACCESS_KEY>", :google_storage_secret_access_key=>"<SECRET>"}, :fog_directory=>"<BUCKET_NAME>"}, @post_processing=true, @queued_for_delete=[], @queued_for_write={}, @errors={}, @dirty=false, @interpolator=Paperclip::Interpolations, @url_generator=#<Paperclip::UrlGenerator:0x000000065ff798 @attachment=#<Paperclip::Attachment:0x000000065ff8d8 ...>, @attachment_options={:convert_options=>{}, :default_style=>:original, :default_url=>"/assets/generic-avatar.png", :escape_url=>true, :restricted_characters=>/[&$+,\/:;=?@<>\[\]\{\}\|\\\^~%# ]/, :filename_cleaner=>nil, :hash_data=>":class/:attachment/:id/:style/:updated_at", :hash_digest=>"SHA1", :interpolator=>Paperclip::Interpolations, :only_process=>[], :path=>"user_profile_photos/:id/:style/:filename", :preserve_files=>false, :processors=>[:thumbnail], :source_file_options=>{}, :storage=>:fog, :styles=>{:medium=>"250x150#", :thumb=>"450x350#"}, :url=>":fog_public_url", :url_generator=>Paperclip::UrlGenerator, :use_default_time_zone=>true, :use_timestamp=>true, :whiny=>true, :validate_media_type=>true, :check_validity_before_processing=>true, :fog_credentials=>{:provider=>"Google", :google_storage_access_key_id=>"<ACCESS_KEY>", :google_storage_secret_access_key=>"<SECRET>"}, :fog_directory=>"<BUCKET_NAME>"}>, @source_file_options={}, @whiny=true>
2.3.0 :003 > p.url
 => "https://<BUCKET_NAME>.storage.googleapis.com/user_profile_photos/9/original/2.png?1463753985"
2.3.0 :004 > f = File.new("#{Rails.root}/spec/support/fixtures/generic-avatar.png")
 => #<File:/.../my_web_app/spec/support/fixtures/generic-avatar.png>
2.3.0 :005 > p.photo = f
NoMethodError: undefined method `keys' for nil:NilClass
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/fog-google-0.3.1/lib/fog/storage/google_xml/real.rb:66:in `signature'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/fog-google-0.3.1/lib/fog/storage/google_xml/real.rb:101:in `request'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/fog-google-0.3.1/lib/fog/storage/google_xml/requests/head_object.rb:36:in `head_object'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/fog-google-0.3.1/lib/fog/storage/google_xml/models/files.rb:81:in `head'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/storage/fog.rb:61:in `exists?'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:558:in `block in queue_all_for_delete'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:557:in `map'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:557:in `queue_all_for_delete'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:251:in `clear'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/attachment.rb:103:in `assign'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/paperclip-4.3.6/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
  from (irb):5
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /home/jignesh/.rvm/gems/ruby-2.3.0@my_web_app/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:9:in `require'
  from bin/rails:9:in `<main>'2.3.0 :006 >
```

Note: Updating an already uploaded photo using Paperclip works correctly when using its `File` storage. 

Can anybody please confirm if this is a bug or a known bug or I am missing something critical which is causing this?

Thanks.

**Comment by Temikus** [comment]
@jiggneshhgohel Thank you for reporting this!

Regression in https://github.com/fog/fog-google/commit/e65ca9f439f59b69173d645b4ce56e09d7bf5bbb#diff-01fcf4c458e26458e0feebb589bce1c5L67

`(params[:query] || {})` was replaced with `params.fetch(:query, {})`
However, fetch still returns `nil` if the actual key is set to it unlike the previous implementation.

PR Submitted.

**Comment by jiggneshhgohel** [comment]
@Temikus thanks for confirming and fixing this issue.

I noticed that PR I merged. Wanted to know by when can I expect the fixes to be released? Meanwhile I will update my Gemfile to use the master branch codebase and verify the issues I am facing in my application.

**Comment by Temikus** [comment]
@jiggneshhgohel I plan to release it ASAP. Please, note that Github is experiencing an outage so make sure it's actually checking out proper files and not an outdated copy (I made changes right as the outage started :/).

**Comment by jiggneshhgohel** [comment]
That's great news. Thanks for the update.

**Comment by Temikus** [comment]
@jiggneshhgohel 0.3.2 should now be public. Resolving.
Feel free to reopen if you have any issues.

**Comment by jiggneshhgohel** [comment]
@Temikus The fixes worked. Thanks.
