### ISSUE TITLE
Storage json api doesn't support directories.all

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#144]
Looks like it was left unimplemented.

```ruby
irb(main):008:0* Fog::Storage::Google.new.directories.all
NoMethodError: undefined method `all' for #<Fog::Storage::GoogleJSON::Directories:0x007ffa10a80950>
        from (irb):8
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/console.rb:15:in `run'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:333:in `console'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
        from /home/jsselman/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
        from /home/jsselman/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
        from /home/jsselman/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
```

**Comment by Temikus** [comment]
This requires implementing a `list` request and mapping it appropriately to `all` method:
https://cloud.google.com/storage/docs/json_api/v1/buckets/list
