### ISSUE TITLE
set_disk_auto_delete issue

### ISSUE THREAD

**Issue by idan89** [fog/fog-google#166]
Hey there!
After creating a new server, I want to set the disk to auto delete when deleting the server in the future.
I saw that there is a function set_disk_auto_delete(auto_delete, device_name)

This is what Im doing:

```
...
random = SecureRandom.hex(6)
name = "server-id-#{random}"

disk = connection.disks.create(
  :name => name,
  :size_gb => 30,
  :zone_name => "us-central1-b",
  :source_image => "custom-image")

disk.wait_for { disk.ready? }

server = connection.servers.create(
  :name => name,
  :disks => [disk],
  :machine_type => "g1-small",
  :zone_name => "us-central1-b",
  :can_ip_forward => true)

# Wait_for routine copied here to show errors, if necessary.
duration = 0
interval = 10
timeout = 600
start = Time.now
until server.ready? || duration > timeout
  puts " ----- "

  server.reload

  puts "ready?: #{server.ready?}"
  puts "public_ip_address: #{server.public_ip_address.inspect}"

  sleep(interval.to_f)
  duration = Time.now - start
end

server.set_disk_auto_delete(true,name);
```

And the result is:

```
----- 
ready?: false
public_ip_address: nil
----- 
ready?: true
public_ip_address: "PUBLIC_IP"
/path/lib/fog/google/shared.rb:183:in `build_excon_response': No attached disk found with device name 'server-id-47e428b15f89' (Fog::Errors::Error)
    from /path/lib/fog/google/shared.rb:154:in `request'
    from /path/lib/fog/compute/google/requests/get_zone_operation.rb:48:in `get_zone_operation'
    from /path/lib/fog/compute/google/models/operations.rb:20:in `get'
    from /path/lib/fog/compute/google/models/server.rb:169:in `set_disk_auto_delete'
    from tasks/create_instance.rb:57:in `<main>'
```

Im using the name of the server/disk that I created as the device_name.

I have found that the server has the following deviceName: "deviceName"=>"persistent-disk-0"
How can I set a different deviceName for the disk?

Thank you!

**Comment by idan89** [comment]
anyone? Thx!

**Comment by icco** [comment]
Weird. What if you change that line to `server.set_disk_auto_delete(true, disk.name);`?

**Comment by Temikus** [comment]
Hah, I can reproduce it:

```
random = SecureRandom.hex(6)
name = "server-id-#{random}"

disk = connection.disks.create(
  :name => name,
  :size_gb => 30,
  :zone_name => "us-central1-b",
  :source_image => "debian-7-wheezy-v20151104")

disk.wait_for { disk.ready? }

server = connection.servers.create(
  :name => name,
  :disks => [disk],
  :machine_type => "g1-small",
  :zone_name => "us-central1-b",
  :can_ip_forward => true)
```

Resulting object:
```
> server
=>   <Fog::Compute::Google::Server
    name="server-id-cdc128b11b50",
...
    disks=[{"kind"=>"compute#attachedDisk", "type"=>"PERSISTENT", "mode"=>"READ_WRITE", "source"=>"https://www.googleapis.com/compute/v1/projects/xxxxx/zones/us-central1-b/disks/server-id-cdc128b11b50", "deviceName"=>"persistent-disk-0", "index"=>0, "boot"=>true, "autoDelete"=>false, "interface"=>"SCSI"}],
 ...
```
Seems like the `instance.disks` and the actual `disk` resource no longer match in names:
```
> server.disks
=> [{"kind"=>"compute#attachedDisk",
  "type"=>"PERSISTENT",
  "mode"=>"READ_WRITE",
  "source"=>"https://www.googleapis.com/compute/v1/projects/graphite-xxx/zones/us-central1-b/disks/server-id-f9aff66300b0",
  "deviceName"=>"persistent-disk-0",
  "index"=>0,
  "boot"=>true,
  "autoDelete"=>false,
  "interface"=>"SCSI"}]

> disk
=>   <Fog::Compute::Google::Disk
    name="server-id-f9aff66300b0",
...
  >
```


This is bizzare, since Console behaviour is different.
Thanks for bringing this to my attention @idan89 , I'll try to get to the bottom of this.

Meanwhile, we probably should implement some kind of logic around `service.instance` calls that looks up the device name by disk reference...

**Comment by idan89** [comment]
Thank for the response @Temikus 
I am using the following workaround

`server.set_disk_auto_delete(true,server.disks[0]['deviceName']);`

**Comment by icco** [comment]
Oh that's super weird. Thanks for tracking down @Temikus

**Comment by Temikus** [comment]
@idan89 Submitted a PR, this should address your use-case while keeping our logic relatively simple.
