### ISSUE TITLE
servers#bootstrap times out

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#200]
Not sure if I'm doing something wrong or not, but I'm unable to bootstrap a server using a public/private ssh key that I generated. Looks like the server is provisioned but it's timed out when attempting to ssh.

Test snippet:
```ruby
  def test_bootstrap
    # Before we start, let's create a public/private key pair
    k = SSHKey.generate(
      :type    => "RSA",
      :bits    => 2048,
      :comment => "Autogenerated by TestBootstrap test"
    )

    g = Fog::Compute::Google.new
    g.servers.bootstrap(
      :private_key => k.private_key,
      :public_key  => k.public_key
    )
  end
```

Output:
```
  1) Error:
TestBootstrap#test_bootstrap:
Fog::Errors::TimeoutError: The specified wait_for timeout (600 seconds) was exceeded
    /Users/jsselman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:9:in `block in wait_for'
    /Users/jsselman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `loop'
    /Users/jsselman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `wait_for'
    /Users/jsselman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fog-core-1.43.0/lib/fog/core/model.rb:69:in `wait_for'
    /Users/jsselman/src/fog-google/lib/fog/compute/google/models/servers.rb:70:in `bootstrap'
    test/integration/compute/test_bootstrap.rb:14:in `test_bootstrap'
```

**Comment by icco** [comment]
Hmm, can you look at the network attached to the instance created @selmanj? Does the default network have ssh open? It used to by default, but it's possible that's changed.

**Comment by Temikus** [comment]
Hmmm, something strange's definitely going on. As an additional note, the warning about highline/termios is gone:
```
λ bundle exec ruby examples/bootstrap.rb
Enter passphrase for <key in memory>:redacted
Enter passphrase for <key in memory>:redacted
Enter passphrase for <key in memory>:redacted
Enter passphrase for <key in memory>:Enter passphrase for <key in memory>:^C/Users/temikus/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:11:in `sleep': Interrupt
	from /Users/temikus/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:11:in `block in wait_for'
	from /Users/temikus/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `loop'
	from /Users/temikus/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	from /Users/temikus/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/fog-core-1.43.0/lib/fog/core/model.rb:69:in `wait_for'
	from /Users/temikus/Code/fog-google/lib/fog/compute/google/models/servers.rb:70:in `bootstrap'
	from examples/bootstrap.rb:12:in `test'
	from examples/bootstrap.rb:19:in `<main>'
```

**Comment by Temikus** [comment]
Everything's working correctly.

Here's your problem:
```
λ bundle exec rake console
[1] pry(main)> k = SSHKey.generate(
[1] pry(main)*   :type    => "RSA",
[1] pry(main)*   :bits    => 2048,
[1] pry(main)*   :comment => "Autogenerated by TestBootstrap test"
[1] pry(main)* )
=> #<SSHKey:0x007fb23e538e80 @comment="Autogenerated by TestBootstrap test", @directives=[], @key_object=#<OpenSSL::PKey::RSA:0x007fb23e538d90>, @passphrase=nil, @type="rsa">
[2] pry(main)> k.public_key
=> "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApI2oRTBCuQly+3CueKx9\nT6ijaFCHEibcOTMqB75uEJfK/lcn2UEKevVI8ZwwUxzn/5y5TanX6CDcuDTX4YUg\nQJkBoUNu/m77Kbbpcmffu6JLVeW/ZYnETrI17NdLcjLkUzYJnrOb2VtKa6iF7M70\nFl3TLtWJ9w09qXrtHcS5up9bMMD2b2hdqNoAodTISs/1ugVvO4377srVgZ55IpoB\neazcsKHIKcr15vuEdZnbLAWG0QLT5es6AZCz/L9mhWNgCs4zoP0HF8Zwgjzbha2Y\nA08sUOaeTaFdRaXmwNx2BNf0ei4yM7nGQOtmvt43dTgsxT7Qzq5Jzb7tMOJgV1lX\nGwIDAQAB\n-----END PUBLIC KEY-----\n"
```
