### ISSUE TITLE
Investigate failing tests in ssh metadata

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#219]
Something changed causing tests to fail :|
```
2.1.7 ~/Code/fog-devel/fog-google  (test_workflow*)-temikus@google.com [16:37:06]∞
temikus λ rake test                                                                                                                                                     (1)
Run options: --seed 15446

# Running:

............EE......

Finished in 137.918791s, 0.1450 runs/s, 0.4495 assertions/s.

  1) Error:
UnitTestServer#test_add_ssh_key_uses_ssh_keys_by_default:
ArgumentError: service, identity and zone are required for this operation
    /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/fog-core-1.43.0/lib/fog/core/attributes.rb:157:in `requires'
    /Users/temikus/Code/fog-devel/fog-google/lib/fog/compute/google/models/server.rb:188:in `set_metadata'
    /Users/temikus/Code/fog-devel/fog-google/lib/fog/compute/google/models/server.rb:214:in `add_ssh_key'
    /Users/temikus/Code/fog-devel/fog-google/test/unit/compute/test_server.rb:15:in `test_add_ssh_key_uses_ssh_keys_by_default'


  2) Error:
UnitTestServer#test_metadata_uses_deprecated_sshKeys_if_exists:
ArgumentError: service, identity and zone are required for this operation
    /Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/fog-core-1.43.0/lib/fog/core/attributes.rb:157:in `requires'
    /Users/temikus/Code/fog-devel/fog-google/lib/fog/compute/google/models/server.rb:188:in `set_metadata'
    /Users/temikus/Code/fog-devel/fog-google/lib/fog/compute/google/models/server.rb:214:in `add_ssh_key'
    /Users/temikus/Code/fog-devel/fog-google/test/unit/compute/test_server.rb:7:in `test_metadata_uses_deprecated_sshKeys_if_exists'

20 runs, 62 assertions, 0 failures, 2 errors, 0 skips


rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-11.2.2/lib" "/Users/temikus/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by Temikus** [comment]
No longer relevant.
