### ISSUE TITLE
Instance create workflow is broken

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#315]
Basic examples no longer work:

```
[2] pry(main)> disk = connection.disks.create(
[2] pry(main)*   :name => "fog-smoke-test-#{Time.now.to_i}",
[2] pry(main)*   :size_gb => 10,
[2] pry(main)*   :zone_name => "us-central1-f",
[2] pry(main)*   :source_image => "debian-8-jessie-v20161215"
[2] pry(main)* )
Google::Apis::ClientError: invalid: Invalid value for field 'sourceImage': 'debian-8-jessie-v20161215'. The URL is malformed.
from /Users/temikus/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:218:in `check_status'
```
- This doesn't work due to new google API client no longer accepting source_image in non-url encoded string.

```
[4] pry(main)> server = connection.servers.create(
[4] pry(main)*   :name => "fog-smoke-test-#{Time.now.to_i}",
[4] pry(main)*   :disks => [disk],
[4] pry(main)*   :machine_type => "n1-standard-1",
[4] pry(main)*   :private_key_path => File.expand_path("~/.ssh/id_rsa"),
[4] pry(main)*   :public_key_path => File.expand_path("~/.ssh/id_rsa.pub"),
[4] pry(main)*   :zone_name => "us-central1-f",
[4] pry(main)*   :username => ENV["USER"],
[4] pry(main)*   :tags => ["fog"],
[4] pry(main)*   :service_accounts => %w(sql-admin bigquery https://www.googleapis.com/auth/compute)
[4] pry(main)* )
ArgumentError: zone is required for this operation
from /Users/temikus/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/fog-core-2.1.0/lib/fog/core/attributes.rb:155:in `requires'
```
- This I'm still figuring out.

**Comment by Temikus** [comment]
Ok, so for instance - zone_name alias was removed in https://github.com/fog/fog-google/commit/f14b3b996fa8b5806b142e3260434307e3e8566f

@emilymye - can you let me know why :zone_name alias was removed? Was it because of the method with the same name? I'm asking since I want to make sure I'm not going to break anything if I add it back.

So far I can either:
- Add it back with a deprecation error and deprecate it and all other :zone_name aliases in 3.0. (we have one in disks and instance groups as well)
or
- Add a deprecation note about it so we fail with a user friendly error to those who still use :zone_name
@icco - WDYT?

**Comment by emilymye** [comment]
@Temikus  I think I removed the set method/attribute because it seemed redundant with `zone` and didn't populate unless you've created the instance using `zone_name`. If you set the `zone` to the `zone name` (i.e. use `:zone => 'us-central1-f`), create will still work since it uses the `zone_name` function, but any imported resource (i.e. read from GCP) will have the proper full zone and the `zone_name` will be calculated correctly. I'd prefer the deprecation note.

**Comment by undead-osiris** [comment]
the same issue

**Comment by Temikus** [comment]
@undead-osiris :source_image should be fixed now. What version are you using?
