### ISSUE TITLE
"Google::Apis::TransmissionError: execution expired" on large files

### ISSUE THREAD

**Issue by mathportillo** [fog/fog-google#323]
Hello,
First, thanks a lot for this gem!
I am getting the above error when uploading large files (1GB)
I am trying to find a way to define timeout seconds for write operations.
I've searched everywhere on fog repo, paperclip repo, google-api-ruby-client repo, and this repo.

Here is the stack trace (gem versions are shown with it):
```
Caused by:
Google::Apis::TransmissionError: execution expired
[...]/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:508:in `dump'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
[...]/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
[...]/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
[...]/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
[...]/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
[...]/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
[...]/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
[...]/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
[...]/google-api-client-0.19.8/lib/google/apis/core/upload.rb:228:in `send_upload_command'
[...]/google-api-client-0.19.8/lib/google/apis/core/upload.rb:254:in `execute_once'
[...]/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
[...]/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
[...]/retriable-3.1.1/lib/retriable.rb:57:in `times'
[...]/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
[...]/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:101:in `block in execute'
[...]/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
[...]/retriable-3.1.1/lib/retriable.rb:57:in `times'
[...]/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
[...]/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:93:in `execute'
[...]/google-api-client-0.19.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
[...]/google-api-client-0.19.8/generated/google/apis/storage_v1/service.rb:1981:in `insert_object'
[...]/fog-google-1.3.3/lib/fog/storage/google_json/requests/put_object.rb:66:in `put_object'
[...]/fog-google-1.3.3/lib/fog/storage/google_json/models/file.rb:78:in `save'
[...]/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
[...]/paperclip-5.2.1/lib/paperclip/storage/fog.rb:115:in `block in flush_writes'
[...]/paperclip-5.2.1/lib/paperclip/storage/fog.rb:104:in `each'
[...]/paperclip-5.2.1/lib/paperclip/storage/fog.rb:104:in `flush_writes'
[...]/paperclip-5.2.1/lib/paperclip/attachment.rb:247:in `save'
[...]/paperclip-5.2.1/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `instance_exec'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `block in invoke_after'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `each'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `invoke_after'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
[...]/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
[...]/activerecord-5.1.6/lib/active_record/callbacks.rb:336:in `create_or_update'
[...]/activerecord-5.1.6/lib/active_record/persistence.rb:129:in `save'
[...]/activerecord-5.1.6/lib/active_record/validations.rb:44:in `save'
[...]/activerecord-5.1.6/lib/active_record/attribute_methods/dirty.rb:35:in `save'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
[...]/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
[...]/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
[...]/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
[...]/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:308:in `block in save'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
[...]/activerecord-5.1.6/lib/active_record/transactions.rb:307:in `save'
[...]/activerecord-5.1.6/lib/active_record/suppressor.rb:42:in `save'
[...]/myproject/lib/tasks/migrate_old_data.rake:22:in `block (2 levels) in <top (required)>'
[...]/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
[...]/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
[...]/myproject/lib/tasks/migrate_old_data.rake:5:in `block in <top (required)>'
[...]/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
[...]/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
[...]/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
[...]/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
[...]/myproject/bin/rails:9:in `require'
[...]/myproject/bin/rails:9:in `<top (required)>'
[...]/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
[...]/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
[...]/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
[...]/spring-2.0.2/lib/spring/client.rb:30:in `run'
[...]/spring-2.0.2/bin/spring:49:in `<top (required)>'
[...]/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
[...]/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
[...]/myproject/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
HTTPClient::SendTimeoutError: execution expired
[...]/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:80:in `<<'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:582:in `dump_file'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:508:in `dump'
[...]/httpclient-2.8.3/lib/httpclient/http.rb:962:in `dump'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:517:in `block in query'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
[...]/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
[...]/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
[...]/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
[...]/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
[...]/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
[...]/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
[...]/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
[...]/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
[...]
```

Thanks a lot!

**Comment by icco** [comment]
As far as I know, that information isn't surfaced to us. We probably need to modify how we do uploads to support this function: https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload

**Comment by mathportillo** [comment]
shouldn't timeout configuration be enough? is the timeout error from the server part? not client part?

**Comment by icco** [comment]
@mathportillo It's a google server config from what I can tell. Google basically says if your object is larger than 5MB you need to be using the resumable upload API call. 

I'm not going to have time to work on this for a while, but maybe @erjohnso or @Temikus can find some time?

**Comment by Temikus** [comment]
I'm not very familiar with the storage side of things so this may take me a while.

@mathportillo Can you give me a repro snippet? Or would something like this work?

```
  connection = Fog::Storage::Google.new
  connection.put_bucket("fog-test", predefined_acl: "publicReadWrite")
  connection.put_object("fog-test", "my file", File.new("testfile", "r"))
```

If I have something I can readily run I can focus on API side of things, where I'm a bit more comfortable.

**Comment by andir** [comment]
I am running into the same issue. Not a ruby developer so not that familiar with how to fix this. Is there still anything I can do to help?

**Comment by shinmyung0** [comment]
Any news on this issue?

**Comment by stanhu** [comment]
@Temikus Ok, it looks like this is easy to support after all. By default, google-api-client **does** support resumable uploads, but the default retries is set to 0 (https://github.com/googleapis/google-api-ruby-client#errors--retries). You can see even in the stack trace above that the `Retriable` block gracefully handles `Google::Apis::TransmissionError`: https://github.com/googleapis/google-api-ruby-client/blob/5b2bdc6342889fe55d78e84ad177bd4d1653bbd3/lib/google/apis/core/http_command.rb#L102-L105

There are two ways to set this. You can globally set this via:

```ruby
require 'google/apis/storage_v1beta2'
Google::Apis::RequestOptions.default.retries = 5
```

Otherwise, I think we just need to document passing in `retries` like so:

```ruby
settings = { provider: 'Google', google_project: 'my-project', google_json_key_location: 'my-creds.json' }

client = Fog::Storage.new(settings)
file = File.open('large_file.gz')
client.put_object('bucket', 'filename.gz', file, retries: 5)
```

I've verified that these settings do work, except recently I've been able to upload 3 TB test files without a single retry, although I am testing from a Google Cloud virtual machine. 🤷‍♂

**Comment by shinmyung0** [comment]
Has there been a PR on this issue?

**Comment by Temikus** [comment]
@shinmyung0 No, I haven't seen one at least.

**Comment by stanhu** [comment]
https://github.com/fog/fog-google/pull/560 should help.
