### ISSUE TITLE
Image create example is broken

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-google#40]
I'm using https://github.com/fog/fog/blob/master/lib/fog/google/examples/image_create.rb as a template. Specifically, at least two different issues:

First, `connection.image.create` should be `connection.images.create` -- trivial fix

Second, `connection.images.create` fails with:

```
/home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-1.23.0/lib/fog/google/compute.rb:179:in `build_excon_response': Invalid value for field 'image.hasRawDisk': 'false'.  (Fog::Errors::Error)
        from /home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-1.23.0/lib/fog/google/compute.rb:959:in `build_response'
        from /home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-1.23.0/lib/fog/google/requests/compute/get_global_operation.rb:21:in `get_global_operation'
        from /home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-1.23.0/lib/fog/google/models/compute/operations.rb:27:in `get'
        from /home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-1.23.0/lib/fog/google/models/compute/image.rb:79:in `save'
        from /home/diwaker/.rvm/gems/ruby-2.0.0-p195@mgt_console/gems/fog-core-1.23.0/lib/fog/core/collection.rb:51:in `create'
```

**Comment by plribeiro3000** [comment]
The original issue was reported by @diwakergupta at fog/fog#3083.

cc/ @diwakergupta @erjohnso @snyquist2 @icco @geemus @migmartri

**Comment by Temikus** [comment]
@migmartri - are you sure you're pointing the link to a valid Google Storage URL?

The following code works without issues for me on fog-google master as of https://github.com/fog/fog-google/commit/b062c2431dbc74bbb28af19e995d58899c13c1c2:
```
def test
  connection = Fog::Compute.new({ :provider => "Google" })

  rawdisk = {
    :source         => 'http://storage.googleapis.com/fog-test-bucket/fog-test-raw-disk-source.image.tar.gz',
    :container_type => 'TAR',
  }

  # Can't test this unless the 'source' points to a valid URL
  return if rawdisk[:source].nil?

  img = connection.images.create(:name             => 'test-image',
                                :description      => 'Test image (via fog)',
                                :raw_disk         => rawdisk)

  img.reload # will raise if image was not saved correctly
end

test
```
PR coming shortly to fix the ambiguous `'http://some_valid_url_to_rootfs_tarball' ` comment.
